name: Build SAMP Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Repozitoriyanı yüklə (Checkout)
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Java JDK quraşdır
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8' # Köhnə Gradle (6.5) üçün ən stabil versiya budur

      - name: Gradle Cache qur
        uses: gradle/actions/setup-gradle@v3

      - name: gradlew üçün icra icazəsi ver
        run: chmod +x ./gradlew

      - name: Debug APK-nı Build et
        run: ./gradlew assembleDebug

      - name: Hazır APK faylını yüklə (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: SAMP-Client-APK
          path: app/build/outputs/apk/debug/*.apk
